spring:
  datasource:
    username: root
    password: 123123
    url: jdbc:mysql://localhost:3306/spb?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10485760
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10s


server:
  port: 8888

mybatis-plus:
  type-aliases-package: com.soft.spb.pojo.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

dubbo:
  application:
    name: web-server
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.soft.spb.service