spring:
   datasource:
      username: xiaowo_root
      password: Xiaowo_mysql
      url: jdbc:mysql://rm-bp1itj68te5655569ro.mysql.rds.aliyuncs.com/spb?useUnicode=true&characterEncoding=utf-8&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8888

mybatis:
   type-aliases-package: com.soft.spb.pojo.entity
   mapper-locations: classpath*:mybatis/mapper/*.xml
